###*
# Faux db.
###

items = []

###*
# GET all items.
###

###*
# Index of `id` in db.
###

indexOf = (id) ->
  i = 0
  len = items.length
  while i < len
    if id == items[i].id
      return i
    ++i
  return

exports.all = (req, res) ->
  res.send items
  return

###*
# POST a new item.
###

exports.create = (req, res) ->
  item = req.body
  id = items.push(item) - 1
  item.id = id
  res.send id: id
  return

###*
# DELETE item :id.
###

exports.remove = (req, res) ->
  id = req.params.id
  i = indexOf(id)
  items.splice i, 1
  res.sendStatus 200
  return

###*
# PUT changes to item :id.
###

exports.update = (req, res) ->
  id = req.params.id
  i = indexOf(id)
  body = req.body
  item = items[i]
  if !item
    return res.send(404, 'item does not exist')
  item.title = body.title
  item.complete = body.complete
  res.sendStatus 200
  return

# ---
# generated by js2coffee 2.0.1