###*
# Module dependencies.
###

Item = require('item')
ItemPresenter = require('item-presenter')
Collection = require('collection')
keyname = require('keyname')
page = require('page')

###*
# Collection of todo Items.
###

items = new Collection

###*
# Todo input.
###

input = document.querySelector('[name=todo]')

###*
# Todo list.
###

list = document.querySelector('#todos')

###*
# Handle keydown.
###

input.onkeydown = (e) ->
  switch keyname(e.which)
    when 'enter'
      # input
      str = e.target.value
      if '' == str.trim()
        return
      e.target.value = ''
      # item
      item = new Item(title: str)
      items.push item
      item.save()
      # presenter
      presenter = new ItemPresenter(item)
      list.appendChild presenter.view.el
  return

###*
# Clear list.
###

page '*', (ctx, next) ->
  list.innerHTML = ''
  next()
  return

###*
# All items.
###

page '/', ->
  Item.all (err, items) ->
    items.each (item) ->
      presenter = new ItemPresenter(item)
      list.appendChild presenter.view.el
      return
    return
  return

###*
# Completed items.
###

page '/complete', ->
  Item.all (err, items) ->
    items.select('complete()').each (item) ->
      presenter = new ItemPresenter(item)
      list.appendChild presenter.view.el
      return
    return
  return

###*
# Incomplete items.
###

page '/incomplete', ->
  Item.all (err, items) ->
    items.reject('complete()').each (item) ->
      presenter = new ItemPresenter(item)
      list.appendChild presenter.view.el
      return
    return
  return
page()

# ---
# generated by js2coffee 2.0.1